openapi: 3.0.1
info:
  title: helloTestISAPI
  description: API Definition of helloTestISAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/hello/is
paths:
  /:
    get:
      responses:
        default:
          description: Default response
